replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-typ/fruit@sha256:0d67c1e9a5d8e4b604bcd3959a63a952dfad8309bc0429a25d5aadfe071db33c # written by ploigos-step-runner
