replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-typ/fruit@sha256:efabca7c0034dd3f82c33162298b57d9954e1e38204e5d40ed3c6b689ecdf557 # written by ploigos-step-runner
