replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-typ/fruit@sha256:a98522c006a759ee5e255d22f8c06ab7bcb72cc1354e2d8c04c113f57c37041e # written by ploigos-step-runner
