replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-typ/fruit@sha256:37ad01d28a38cf608353f9983e325aa4152ae42d78fc114eee4461894115318a # written by ploigos-step-runner
