replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-typ/fruit@sha256:e7996b3402823c6fe952cf9cb17ed021f315defe42c34ac42eafd1c5438b2ee6 # written by ploigos-step-runner
