replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-typ/fruit@sha256:841d5ffc9de49e62e5ab06455c1dad97f238d1c507991ceacbdfadede66a6bac # written by ploigos-step-runner
